artifact_location: file:///E:/projects/weapon-detection/runs/mlflow/244413357406398666
creation_time: 1779470088715
experiment_id: '244413357406398666'
last_update_time: 1779470088715
lifecycle_stage: active
name: /Shared/Ultralytics
workspace: default
